spring.application.name: pet-project-services

app:
  scheduling:
    check-interval: PT30S
  time-after-request-to-work:
    minutes: 5
    hours: 72

kafka.bootstrapServers: 'localhost:9090'

server.port: 8088
spring:
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5430/services-db'
    username: postgres
    password: postgres

  liquibase:
    url: 'jdbc:postgresql://localhost:5430/services-db'
    user: postgres
    password: postgres
    change-log: 'classpath:db/changelog/changelog-master.xml'