spring.application.name: pet-project-services
server.port: 8088

app:
  scheduling:
    enabled: true
    check-interval: PT30S
  time-after-request-to-work:
    minutes: 5
    hours: 0

kafka.bootstrapServers: 'localhost:9090'

spring:
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5430/services-db'
    username: postgres
    password: postgres

  liquibase:
    url: 'jdbc:postgresql://localhost:5430/services-db'
    user: postgres
    password: postgres
    change-log: 'classpath:db/changelog/changelog-master.xml'

# Metrics
management:
  endpoints.web.exposure.include: prometheus,health,info,metrics
  metrics:
    tags.application: ${spring.application.name}
    export:
      prometheus.enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
